### ISSUE TITLE
Carrer Service rate is not exact that is supplied from the app

### ISSUE THREAD

**Issue by msonowal** [Shopify/shipping-fulfillment-app#15]
Hi there, As I have tried reaching shopify support they also have no clue thought someone may have the answer here.
So here it goes

I am trying to use Carrier Service API to use calculated rate at checkout for one of the clients.
and below is the value I am returning which shows the price in INR i.e. 1326.74 in rupees and I am also returning the currency as it is.
But in checkout page of the store it shows in doller (store currency) which is fine but it displays $ 0.18 as the rate which is no where near no the value of 1326.74 even after conversion i.e. INR to USD
so if the value for conversion say this 
`1 USD = 74.530 INR`
it should be 
`17.80 USD = 1326.74 INR`

Please let me know what could be wrong

```json
{
  "rates": [
    {
      "service_name": "DHL manash",
      "service_code": "dhl_in_cust",
      "currency": "INR",
      "total_price": 1326.74,
      "description": "Preferred Shipping for the Order"
    }
  ]
}
```

**Comment by jnormore** [comment]
Try a total price of 132674, the value should be the integer including any minor currency units (cents).

**Comment by msonowal** [comment]
so as it is INR it will be in paisa which will be 1326.74 * 100  = 132674.

But the documentations were nowhere mentioned so I was just curious

**Comment by mash** [comment]
@jnormore please document this in https://shopify.dev/docs/admin-api/rest/reference/shipping-and-fulfillment/carrierservice

**Comment by jnormore** [comment]
Sorry @mash I'm not with Shopify anymore, I only responded to this issue because I forgot to turn off notifications on it a few years ago.

@jonathankwok you look active on some shipping stuff still, any chance you can forward this request to someone? Thanks and hope you're doing well :)

**Comment by georgetzavelas** [comment]
@jnormore hope all is well with you! @mash My team owns this domain so we will look at updates to the docs.
